eezcommerce/eezcommerce

envExample.txt, public/css/main.css, public/index.html
also added a .env example file
=> Updating homepage to use bootstrap

envExample.txt, index.js, modules/emailService.js, package-lock.json, package.json
Email for dummy users can be verified via an emailed secret link. Proof-of-concept level code, obviously needs to be hooked into actual database + worked into setup workflow.
to use:
1. update one of the dummy users with your email in /modules/emailService.js (it won't send email if the email isn't registered to prevent spam)
1. Ensure email username & password are in .env as per example
1. hit /verification_email_test/youremail@email.com
1. wait for verification email to be sent
1. click link in email to verify email
**NOTE** port 587 must be open on your firewall, seneca wifi blocks at the network level it even if your firewall doesn't
Fixes #19
=> Added email verification skeleton

modules/emailService.js
added our email to allow for testing the verify functionality
=> changed email to be testable fixes #21

envExample.txt, modules/emailService.js
fixes #23
new environment variables introduced
=> changed public URL in email link

.gitignore
ignoring /cert path in prep for SSL setup
=> Ignored /cert path

envExample.txt, index.js
updated .env options,
added https server with certificates,
added try...catch block for graceful failure if certificates don't exist
=> Adding SSL

public/views/updateBillingForm.html, public/views/updateEmailForm.html
added views folder and the update Email/Billing fragments
=> added views

public/css/main.css, public/index.html, public/views/updateBillingForm.html, public/views/updateEmailForm.html
we may want to add more items and not sure if we want to add "Membership Type" as the heading.
Currently looks like:
=> Added modal for pricing to show Basic/Premium Memberships

html/orders/orderList.html, html/products/productAdd.html, index.js, package.json, public/index.html, public/views/AccountCreated.html, public/views/CreateCategory.html, public/views/ForgottenPassword.html, public/views/Login.html, public/views/Questions.html, public/views/Signup.html, public/views/updateBillingForm.html, public/views/updateEmailForm.html, public/views/viewProducts.html
fixed viewProducts.html, missing closing tag
=> Fixed prettier printWidth

public/css/main.css, public/index.html, public/js/SignupValidation.js
=> fixed old merge

index.js, modules/userService.js, package-lock.json, package.json, public/index.html, public/views/Dashboard.html
added signup,
added login,
added mongo schemas for user
protected /dashboard
enabled mongo
=> Added auth routes + protected /dashboard

index.js, modules/emailService.js, modules/userService.js, public/index.html, public/views/EmailVerificationSent.html, public/views/ErrorPage.html, public/views/Questions.html
This PR. implements /signup to create, then check for user in database, send an email. and redirect to a sent email confirmation page.
Note:
Token is not currently being used.
Wanted to put token somewhere other than the database so... decided to open new branch
=> Email verification sent

modules/userService.js, public/css/main.css, public/index.html
=> Fixed weird brackets in email service module

index.js, public/css/main.css, public/index.html, public/views/ErrorPage.html
rebase:
also fixed the scroll snapping
added links in footer
routes not yet functional
Minor fixes, including error page
fixed index
=> added simple footer

index.js, modules/userService.js, public/js/SignupValidation.js, public/views/EmailVerified.html
Now uses asynchronus posts to signup or login
This allows for errors to be handled client-side
Other minor improvements like timed redirects
=> Handle signup / login errors

index.js
switch in sendverificationemail broke stuff
urgent
=> hotfix for email sending

index.js, modules/userService.js
if verification email isn't sent, user isnt created (actually, it is, but immediately deleted)
=> Fixed email unsent user bug

index.js, public/js/landingPage.js, public/views/EmailResetSent.html, public/views/ForgottenPassword.html
FINALLY got it to where I want it to be.. Thankss LUCA :pray:
=> Forgot validation

views/addCategoryModal.hbs, views/categories.hbs, views/customize.hbs, views/layouts/dashboard.hbs, views/orders.hbs, views/partials/addCategoryModal.hbs, views/report.hbs
added partials folder for modal templates in hbs
note: they need to be referenced outside body to be shown.
also added a couple of pages to fill the slots
=> Dashboard links

index.js, modules/userService.js, public/js/dashboard.js, views/ForgottenPassword.hbs, views/home.hbs, views/layouts/dashboard.hbs, views/overview.hbs, views/partials/header.hbs, views/products.hbs, views/settings.hbs
Allows for changing of user email or business name
Logged in user data is used for UI element in dashboard
=> User settings

index.js, modules/orderService.js, views/orders.hbs, views/partials/addOrderModal.hbs
Add Order listing and additions
=> Order revised

index.js, modules/Models/OrderModel.js, modules/Models/ProductModel.js, modules/Models/UserModel.js, modules/orderService.js, modules/productService.js, views/orders.hbs, views/partials/ordersDetail.hbs
should list product attached to the order on order details
=> Order detail product list

modules/Models/OrderModel.js, modules/orderService.js
fixing last merge request, had duplicate declaration for ordermodel
=> moved duplicate declaration to model

views/layouts/NavBar.hbs, views/products.hbs
=> fixed events in products

modules/Models/UserModel.js, modules/userService.js, views/settings.hbs
minor changes
fixed up the user model SecQues. subdocument
fixed up forms
=> Added Security Question Validation

views/layouts/dashboard.hbs, views/settings.hbs
More reliably asks user to fill out security questions
uses new handlebar isFalsey helper
=> Security question smallfix

public/css/main.css, views/layouts/NavBar.hbs, views/partials/header.hbs, views/partials/pricingModal.hbs, views/testimonials.hbs
=> Testimonials

index.js, modules/Models/CustomizationModel.js, modules/customizationService.js, modules/orderService.js, modules/productService.js, modules/userService.js, public/css/main.css, views/customize.hbs, views/products.hbs, views/siteViews/home.hbs, views/siteViews/store.hbs
added customization features
also saves them to database
reworked customization UI
end user site is more realistic (needs to be made more modular and re-usable) 
**requires the re-creation of your account (probably)**
=> Better customization

package-lock.json, package.json
=> added multer to package

index.js, modules/Models/CategoryModel.js, modules/Models/ProductModel.js, modules/categoryService.js, modules/productService.js, modules/userService.js, views/categories.hbs, views/partials/addCategoryModal.hbs, views/partials/addProductModal.hbs
may want to create a new account for this one..
+ Model and service for categories
+ routes added for categories
+ categories field added into ProductModel
+Products now takes a category field
+ productService: +counting productsWithCategory method
=> Categories

index.js, views/layouts/dashboard.hbs, views/partials/avatarModal.hbs
404 errors in console no longer show.
=> Avatar not found

index.js, modules/simpleGuard.js
force merging this, 
created a new module for course use
see: https://github.com/lucacataldo/simpleGuard/
=> implement simpleGuard to show emile

index.js, modules/Models/OrderModel.js, modules/Models/UserModel.js, modules/orderService.js, views/orders.hbs, views/partials/ordersDetail.hbs
Reverts eezcommerce/eezcommerce#172
=> Revert "Order dropdown"

modules/Models/UserModel.js, modules/orderService.js, views/orders.hbs
=> Datatable to order

envExample.txt, index.js, modules/orderService.js
It's kinda annoying when you're running locally, created an environment variable to disable it
=> Disable simpleGuard in dev environments

envExample.txt, index.js, modules/Models/ProductModel.js, modules/productService.js
now uses compound index key, blocks at database level
also added process.env.BYPASS_VERIFICATION
=> Product Duplicate Refactor

modules/Models/OrderModel.js, views/orders.hbs
=> Order Subfunctions

index.js, modules/Models/ProductModel.js, modules/orderService.js, modules/productService.js, views/layouts/dashboard.hbs, views/overview.hbs
=> Overview Page improvements

modules/orderService.js, modules/productService.js
Limits fields of tables on the overview page, stops it from overflowing with too many
=> Limit top products and orders to 5

views/layouts/dashboard.hbs
Don't know if we want this but I think it looks better 🤷‍♂
=> [Optional] Dark Mode

views/partials/pricingModal.hbs
Not sure if we want the modal stacked on top of pricing modal or
if we want modal to hide pricing modal and show login modal(reasoning is i may think somoene wants to just easily hide the signup to go back to looking at the pricing)
Please advise @lucacataldo
=> Fixes Pricinglink

index.js, modules/Models/Cart.js, views/overview.hbs, views/siteViews/shoppingCart.hbs, views/siteViews/store.hbs
This patch implements functioning shopping cart:
adds items to cart, 
changes badge number to count items,
calculate total cost of items.
please delete your cookies if you've visited the customer-side website recently.
Apply Coupon, Procced to Checkout, remove item currently not working
=> Add to cart

index.js, modules/Models/Cart.js, views/overview.hbs, views/siteViews/shoppingCart.hbs, views/siteViews/store.hbs
merge this After addToCart.
added Continue shopping
clear - clears all items from shopping cart
remove - removes a single item(all items of that type will be removed)
Wishlist:
removing 1 quantity at a time
=> Remove cart

index.js, public/css/main.css, views/partials/productDetail.hbs, views/products.hbs
reformatted product details and enabled change product image
=> Change prod img

index.js, public/css/main.css, views/partials/productDetail.hbs, views/products.hbs, views/siteViews/home.hbs, views/siteViews/layouts/nav.hbs, views/siteViews/store.hbs
customer website now uses a layout for the navbar
=> Cus partialing

index.js, package-lock.json, package.json, views/layouts/dashboard.hbs, views/partials/avatarModal.hbs, views/siteViews/layouts/nav.hbs, views/siteViews/shoppingCart.hbs
forces the avatar to be a PNG with a max height of 250px for now
png logos didn't work before
transparency didn't work before
also prevents from wasting bandwith / crashing with massive image upload
=> Fix avatar filetype

index.js, modules/Models/UserModel.js, modules/emailService.js, modules/userService.js, views/changePassword.hbs, views/partials/addProductModal.hbs, views/settings.hbs
Can now change password via settings
Can also reset password from link in email
Email link now actually expires after 24hrs
**MAY REQUIRE DATABASE DUMP**
=> Implemented change / reset password

index.js, modules/customizationService.js, package-lock.json, package.json, public/css/main.css, public/js/landingPage.js, views/customize.hbs, views/siteViews/home.hbs, views/siteViews/layouts/nav.hbs, views/siteViews/store.hbs
organizational, UI, bunch of small fixes
=> Cleanup stuff

views/partials/productDetail.hbs, views/partials/shopProductDetail.hbs, views/siteViews/layouts/nav.hbs, views/siteViews/store.hbs
shows detail and description of product when image is clicked.
+/- Quantity button is there but logic is not implemented.
Add to cart button disabled currently
=> shows product detail and quantity change html

index.js, modules/Models/Cart.js, views/partials/productDetail.hbs, views/partials/shopProductDetail.hbs, views/siteViews/layouts/nav.hbs, views/siteViews/store.hbs
implemented selecting quantity to add in shopping cart
=> Shopping qty

index.js, modules/Models/ProductModel.js, modules/emailService.js, modules/orderService.js, public/js/checkout.js, public/test.html, views/siteViews/checkout.hbs, views/siteViews/layouts/nav.hbs, views/siteViews/shoppingCart.hbs, views/siteViews/thanks.hbs
LOTS of things still need to be addressed, but the checkout page is now validated and the email receipt is now improved
=> Checkout validation

index.js, modules/Models/OrderModel.js, modules/orderService.js, views/orders.hbs, views/overview.hbs, views/partials/ordersDetail.hbs, views/siteViews/checkout.hbs
fixed orderModel & related addOrder
=> fixed up addOrder

index.js
=> hotfix oop

index.js, modules/Models/CustomizationModel.js, package-lock.json, package.json, public/css/main.css, public/views/productAdd.html, themes/default.scss, themes/sideBarNav.scss, views/customize.hbs, views/partials/addProductModal.hbs, views/partials/avatarModal.hbs, views/partials/productDetail.hbs, views/siteViews/checkout.hbs, views/siteViews/home.hbs, views/siteViews/layouts/nav.hbs, views/wizardSteps/three.hbs
User can now upload a "featured" image to be displayed on the homepage of the website. For now, it's displayed in the same way for all themes but it can be styled using the `site-feature-image` css class.
=> Upload site images

public/css/main.css, public/css/theme.scss, public/js/landingPage.js, views/home.hbs, views/layouts/NavBar.hbs
Now with a focus on the customer-facing side of things as per Emile's request
Fancy animations
Fancy scroll effects
Removed scroll-jacking
Cited artwork & icons
Changed wording of "Testimonials"
Added Home link
=> New Homepage
